name: HGsons Daily Security Bot

on:

  schedule:
    - cron: '1 21 * * *'

  workflow_dispatch:

jobs:

  run-security-bot:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Security Bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CHAOS_MULTIPLIER: ${{ secrets.CHAOS_MULTIPLIER }}

        run: python send_daily_code_v2.py
